- name: check if .htpasswd file already exists
  stat:
    path: /etc/nginx/.htpasswd
  register: htpasswd_file

- name: remove libapr related packages
  apt:
    pkg:
      - libapr1
      - libaprutil1
    state: absent
    update_cache: yes
    autoremove: yes
  when: not htpasswd_file.stat.exists

- name: install apache2-utils
  apt:
    name: apache2-utils
    state: present
    update_cache: yes

- name: install gnutls-bin
  apt:
    name: gnutls-bin
    state: present
    update_cache: yes

- name: generate .htpasswd file
  shell: |
    set -o pipefail
    htpasswd -bc /etc/nginx/.htpasswd {{ nginx_user }} {{ nginx_password }}
    chmod 600 /etc/nginx/.htpasswd
    chown www-data:www-data /etc/nginx/.htpasswd
  args:
    executable: /bin/bash
  changed_when: true
  tags: molecule-idempotence-notest

- name: create prometheus ssl dir
  file:
    path: /etc/ssl/prometheus
    state: directory
    mode: '0755'

- name: generate prometheus-private-key
  shell: |
    sudo certtool --generate-privkey --outfile /etc/ssl/prometheus/prometheus-private-key.pem
  args:
    executable: /bin/bash
  changed_when: true

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/ssl/prometheus/prometheus-cert.crt
    privatekey_path: /etc/ssl/prometheus/prometheus-private-key.pem
    provider: selfsigned

- name: create nginx config for node exporter
  copy:
    src: node_exporter.nginx.conf
    dest: /etc/nginx/sites-enabled/node-exporter.conf
  when: node_exporter_enabled|bool

- name: create nginx config for polkadex metrics
  copy:
    src: polkadex_metrics.nginx.conf
    dest: /etc/nginx/sites-enabled/polkadex-metrics.conf

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: molecule-idempotence-notest
