---
- name: Wait for system ready
  hosts: validator
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: validator update binary
  hosts: validator
  become: yes
  roles:
  - polkadex-update-binary
